on: 
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: '1.15'

      - uses: actions/checkout@v2

      - name: Download Go modules
        run: go mod download

      - name: Build
        run: go build ./...

      - name: Build Docker
        run: docker build .

  release:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    env:
      IMAGE: docker.io/dvob/http-server
    steps:
      - name: Docker Login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login docker.io -u dvob --password-stdin

      - uses: actions/setup-go@v1
        with:
          go-version: '1.15'

      - uses: actions/checkout@v2

      - name: Download Go modules
        run: go mod download

      - name: Get the version
        run: echo ::set-env name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Docker build
        run: docker build -t tmp .

      - name: Docker tag and push
        run: |
          docker tag tmp ${IMAGE}:${{ env.VERSION }}
          docker tag tmp ${IMAGE}:latest
          docker push ${IMAGE}:${{ env.VERSION }}
          docker push ${IMAGE}:latest

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sudo snap install goreleaser --classic
          goreleaser release
